services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cleanenergy
      POSTGRES_PASSWORD: cleanenergy
      POSTGRES_DB: cleanenergy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
